name: relion-5.0
channels:
  - https://software.repos.intel.com/python/conda
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - python=3.10
  - setuptools=59.5.0
  - pip:
      - intel-extension-for-tensorflow=2.15=*cpu*
      - intel-extension-for-pytorch=2.3.100
      - oneccl_bind_pt=2.3.0 torchvision=0.18.1
      - torchaudio=2.3.1
      - deepspeed=0.14.2
      - neural-compressor=2.5.1
      - xgboost
      - scikit-learn-intelex
      - modin-all
      - torchvision
      - numpy==1.24.4
      - blas=*=*mkl
      - tqdm==4.65.0
      - mrcfile==1.4.3
      - starfile>=0.5.6
      - loguru==0.7.0
      - umap-learn==0.5.3
      - matplotlib==3.7.2
      - napari[all]==0.4.18
      - tsnecuda==3.0.1
      - PyQt5==5.15.9
      - typer==0.9.0
      - biopython==1.81
      - fastcluster==1.2.6
      - seaborn==0.12.2
      - dill==0.3.7
      - pyhmmer>=0.10.1
      - fair-esm
      - einops
      - scipy
      - git+https://github.com/3dem/relion-classranker@b6e751e5cb4205d8e9b36d0ae38c3687b3395acb
      - git+https://github.com/3dem/relion-blush
      - git+https://github.com/3dem/DynaMight
      - git+https://github.com/3dem/topaz
      - git+https://github.com/3dem/model-angelo
      - ".[vis]"
      
      
